### ISSUE TITLE
Errors in the log

### ISSUE THREAD

**Issue by KentEkl** [fred-oranje/rituals-genie#8]
## Version of the custom_component
Latest

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

Logger: homeassistant
Source: custom_components/rituals_genie/switch.py:43
First occurred: 11 februari 2021 17:30:39 (11 occurrences)
Last logged: 15:00:42

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 198, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 676, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/rituals_genie/switch.py", line 43, in is_on
    self.coordinator.data.get("hub").get("attributes").get("fanc", "0") == "1"
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by Veldkornet** [comment]
I also get this error. It was initially working fine though.

**Comment by Veldkornet** [comment]
May be related to [this](https://alerts.home-assistant.io/#rituals_perfume_genie.markdown)

**Comment by Pirol62** [comment]
Got exactly the same error but additionally this one àt the same time:
`````
Logger: custom_components.rituals_genie
Source: custom_components/rituals_genie/api.py:81
Integration: Rituals Genie (documentation, issues)
First occurred: 16. März 2021, 19:00:48 (6 occurrences)
Last logged: 7:32:39

Timeout error fetching information from https://rituals.sense-company.com/api/account/hub/c385f1caaecc41515049b561e7f19bff323dd2b4f1de2230703fcc618a0ca505 -
````

**Comment by Pirol62** [comment]
Will there be any progress on this?

**Comment by Pirol62** [comment]
Already updated to 2021.4.6. The error is still there.

**Comment by Pirol62** [comment]
Moved to the other integration. I can understand, that it is not worth to keep two integrations. But please then communicate that this version here will be not supported anymore. Makes things easier.
